train:
	cd src/train; python3 train.py

deploy_aws:
	cd src/deploy/aws; python3 deployment.py

inference_aws:
	cd src/deploy/aws; python3 inference.py

inference_azure:
	cd src/deploy/azure; python3 inference.py

monitoring:
	cd src/monitoring; python3 monitor.py
